#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright muflax <muflax@gmail.com>, 2009
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

def main():
    pass

if __name__ == "__main__":
    main()

