source 'https://rubygems.org'

# my own stuff
gem "backup-urls", :path => File.expand_path("~/src/backup/backup-urls")
gem "muflax"

# pry
gem "pry"
gem "pry-doc"
gem "pry-docmore"
gem "pry-nav"
gem "pry-rails"
gem "pry-rescue"
gem "pry-theme"
gem "pry-vterm_aliases"

# TAGS
gem "ripper-tags"
gem "gem-ripper-tags"

# rspec
gem "autotest"
gem "rspec"

# music stuff
gem "narray"
gem "fftw3"
gem "ruby-alsa"
gem "ruby-audio"

# gtd
gem "ascii_charts"
gem "beeminder"
gem "future_me"

# lol
gem "lolcommits"

# used by scripts
gem "cinch"
gem "curses"
gem "rake"
gem "rb-inotify"
gem "sqlite3"
gem "unicode_utils"
gem "uuid"

# CLI stuff
gem "pru"

# rbenv
gem "rbenv-rehash"

# meta
gem "treetop"

# profiling
gem "ruby-prof"

# memoization
gem "memoist"
gem "moneta"

# markups
gem "htmlentities"
gem "kramdown"
gem "nokogiri"
gem "org-ruby"
gem "reverse_markdown"
gem "ruby-graphviz"

# gist
gem "jist"

# some generically useful stuff
gem "diff-lcs"
gem "levenshtein-ffi"
gem "ruby-lzma"
gem "systemu"
gem "tidy_ffi"
gem "units"
