source 'https://rubygems.org'

# my own stuff
gem "muflax"

# pry
gem "pry"
gem "pry-doc"
gem "pry-docmore"
gem "pry-nav"
gem "pry-rails"
gem "pry-rescue"
gem "pry-theme"
gem "pry-vterm_aliases"

# testing
gem "minitest"
gem "maxitest"

# gtd
gem "ascii_charts"

# lol
gem "lolcommits"

# used by scripts
gem "cinch"
gem "curses"
gem "rake"
gem "rb-inotify"
gem "sqlite3"
gem "t"
gem "unicode_utils"
gem "uuid"

# profiling
gem "readygo"
gem "ruby-prof"

# memoization
gem "moneta"

# markups
gem "htmlentities"
gem "kramdown"
gem "nokogiri"
gem "reverse_markdown"
gem "ruby-graphviz"

# some generically useful stuff
gem "diff-lcs"
gem "levenshtein-ffi"
gem "ruby-lzma"
gem "systemu"
gem "tidy_ffi"
gem "values"
