source 'https://rubygems.org'

# my own stuff
gem "backup-urls", :path => File.expand_path("~/src/backup/backup-urls")
gem "bayescraft"
gem "muflax"

# pry
gem "pry"
gem "pry-byebug"
gem "pry-doc"
gem "pry-docmore"
gem "pry-nav"
gem "pry-rails"
gem "pry-rescue"
gem "pry-stack_explorer"
gem "pry-theme"
gem "pry-vterm_aliases"

# TAGS
gem "ripper-tags"
gem "gem-ripper-tags"

# rspec
gem "autotest"
gem "rspec"

# games
gem "gosu"
gem "hasu"
gem "opengl"
gem "rmagick"

# music stuff
gem "narray"
gem "fftw3"
gem "ruby-alsa"
gem "ruby-audio"

# gtd
gem "future_me"

# lol
gem "lolcommits", :path => File.expand_path("~/src/forks/lolcommits")

# used by scripts
gem "moneta"
gem "rb-inotify"
gem "sqlite3"
gem "unicode_utils"
gem "uuid"

# CLI stuff
gem "pru"

# rbenv
gem "rbenv-rehash"

# meta
gem "treetop"

# profiling
gem "ruby-prof"

# some generically useful stuff
gem "kramdown"
gem "nokogiri"
gem "org-ruby"
gem "ruby-graphviz"
gem "systemu"
gem "tidy_ffi"
gem "units"
