#!/bin/zsh
setopt RE_MATCH_PCRE

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Delay item:"
  echo "    delay line [time]"
  echo ""
  exit
}

die()
{
    echo "$*"
    exit 1
}
    
errmsg="usage: $TODO_SH do ITEM#"
do_entries=()

# args
item=$1
shift

if [[ $# -gt 0 ]]; then
    delay=$1
    shift
else
    delay="(+1)"
fi

# check that item is valid
[ -z "$item" ] && die "$errmsg"
[[ "$item" =~ "\d+" ]] || die "$item: not a number"

# ...and has a todo
todo=$(sed "$item!d" "$TODO_FILE")
[ -z "$todo" ] && die "$item: No such todo."

# remove filter
todo=$(ruby -e "puts '$todo'.gsub(/\s*\(\d{2}\/\d{2}\/\d{2}\)/, '')")

# remove old entry
if [ $TODOTXT_PRESERVE_LINE_NUMBERS = 0 ]; then
    # delete line (changes line numbers)
    sed -i.bak -e $item"s/^.*//" -e '/./!d' "$TODO_FILE"
else
    # leave blank line behind (preserves line numbers)
    sed -i.bak -e $item"s/^.*//" "$TODO_FILE"
fi

# call back to the main script
"$TODO_SH" add "$todo" "$delay"
