#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  status:"
  echo "       just like normal ls, but diplays TODO_STATUS afterwards"
  exit
}

TODOTXT_VERBOSE=0 "${TODO_SH}" command ls "$@"
"$TODOTXT_STATUS_PATH"
